# Generated by Django 5.0.4 on 2024-10-18 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('violation_detected', 'Violation Detected')], default='in_progress', max_length=20)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('open_audits', models.IntegerField(default=0)),
                ('violations_detected', models.IntegerField(default=0)),
            ],
        ),
    ]
